# -*- coding: utf-8 -*-
"""
Genera calendario_viral_30dias_rosa_maria.csv — 30 días de contenido viral
escrito a mano (ganchos, idea, CTA) para la marca personal de Rosa María
(fiscalidad + marketing + IA + crecimiento). Cada día indica el formato y el
TIPO DE SLIDE recomendado, usando también los formatos virales nuevos de la
app: chat (captura DM), nota (app de notas) y versus (mito/realidad).
"""
import csv, datetime

INICIO = datetime.date(2026, 7, 10)
DIAS_ES = ["Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"]

# (formato, pilar, tipo_slide, gancho, idea_central, cta)
PLAN = [
 ("Reel","Marketing","nota",
  "No necesitas más seguidores. Necesitas que 100 personas correctas sepan que existes.",
  "La visibilidad no es alcance, es precisión: llegar a quien ya puede comprarte, no a todos.",
  "Guárdalo"),
 ("Carrusel","Fiscalidad","versus",
  "Lo que crees que te ahorra impuestos vs lo que de verdad te los ahorra",
  "Desmontar 3 mitos fiscales del autónomo (gastos, módulos, aplazamientos) con la versión correcta.",
  "Compártelo con tu gestor"),
 ("Post","Mentalidad","frase",
  "Tu facturación es el espejo de tus hábitos, no de tu suerte.",
  "Reflexión sobre constancia y sistema: los negocios estables se construyen, no se ganan en una rifa.",
  "Cuéntame tu caso"),
 ("Reel","IA","chat",
  "El mensaje que me mandó un cliente después de automatizar su semana",
  "DM real: pasó de perder 10h/semana en tareas repetitivas a delegarlas en la IA.",
  "Escríbeme IA"),
 ("Carrusel","Autoridad","lista",
  "5 señales de que tu empresa es mejor de lo que el mercado cree",
  "Diagnóstico honesto: buen producto + mala visibilidad = techo de crecimiento invisible.",
  "Guárdalo para revisarlo"),
 ("Historia","Conversión","chat",
  "Así empieza siempre una conversación que acaba en cliente",
  "Captura de un primer mensaje bien planteado: cómo un buen filtro cambia quién te escribe.",
  "Escríbeme ESTRATEGIA"),
 ("Reel","Storytelling","nota",
  "Esta historia explica por qué vender más no siempre es crecer",
  "Caso real de un negocio que facturaba mucho y ganaba poco: el problema no eran las ventas.",
  "Cuéntame si te suena"),
 ("Carrusel","Marketing","versus",
  "Marketing que gusta vs marketing que vende",
  "Diferencia entre contenido que entretiene y contenido que mueve a la acción. Ejemplos de cada uno.",
  "Guárdalo"),
 ("Post","Fiscalidad","frase",
  "El dinero que no controlas hoy es el susto que te llevas en junio.",
  "Micro-hábito fiscal mensual que evita el agobio de la declaración.",
  "Cuéntame cómo lo llevas"),
 ("Reel","IA","versus",
  "Lo que crees que hace la IA vs lo que ya está haciendo por tu competencia",
  "Mito: la IA es para técnicos. Realidad: tu competencia ya la usa para producir el doble.",
  "Escríbeme IA"),
 ("Carrusel","Crecimiento","lista",
  "Por qué unas empresas crecen y otras, haciendo lo mismo, se estancan",
  "3 palancas: visibilidad, números claros y decisiones por datos. La calidad sola no basta.",
  "Guárdalo"),
 ("Historia","Autoridad","nota",
  "Lo que nadie te dice de tener 'buena reputación'",
  "La reputación que no es visible no capta clientes: hay que hacerla pública, no esperar el boca a boca.",
  "Cuéntame tu experiencia"),
 ("Reel","Conversión","chat",
  "El DM que recibo cuando el contenido está bien hecho",
  "Captura de un cliente que llega ya convencido: eso es lo que hace un buen sistema de contenido.",
  "Escríbeme SISTEMA"),
 ("Carrusel","Storytelling","chat",
  "La conversación con un cliente que lo cambió todo",
  "Diálogo real que muestra el momento en que un negocio decide dejar de improvisar.",
  "Guárdalo"),
 ("Post","Mentalidad","frase",
  "No te falta tiempo. Te falta un sistema que no dependa de ti.",
  "Reflexión sobre delegar y sistematizar antes de 'trabajar más horas'.",
  "¿Te pasa? Cuéntamelo"),
 ("Reel","Marketing","nota",
  "Llevo años viendo negocios por dentro. Esto es lo que separa a los que crecen.",
  "Confesión honesta en formato nota: la visibilidad estratégica gana a la suerte, siempre.",
  "Guárdalo"),
 ("Carrusel","Fiscalidad","lista",
  "4 gastos que SÍ puedes deducir y probablemente no estás deduciendo",
  "Educativo claro y práctico, sin tecnicismos, con el porqué de cada uno.",
  "Compártelo con quien lo necesite"),
 ("Reel","IA","chat",
  "Le pedí esto a la IA y me ahorró una tarde entera",
  "Captura de un caso concreto y replicable de automatización con IA para un negocio pequeño.",
  "Escríbeme IA"),
 ("Carrusel","Autoridad","versus",
  "Autoridad real vs postureo en redes",
  "Diferencia entre demostrar criterio con casos y datos, y solo 'parecer' experto.",
  "Guárdalo"),
 ("Historia","Conversión","nota",
  "El cliente perfecto no te encuentra por casualidad",
  "Reflexión: cómo dejar de depender del azar y construir un camino claro hasta ti.",
  "Escríbeme ESTRATEGIA"),
 ("Reel","Crecimiento","versus",
  "Trabajar más vs trabajar con criterio",
  "Mito: más horas = más ingresos. Realidad: mejores decisiones = más margen con menos desgaste.",
  "Guárdalo"),
 ("Carrusel","Marketing","lista",
  "3 errores que hacen que tu contenido no venda (aunque tenga muchas visitas)",
  "Visitas sin conversión: hook flojo, sin llamada clara, hablando a todos y a nadie.",
  "Guárdalo para tu próximo post"),
 ("Post","Fiscalidad","frase",
  "Facturar mucho y ganar poco también es un problema fiscal.",
  "Rentabilidad real vs facturación: mirar el margen, no solo el ingreso.",
  "Cuéntame tu caso"),
 ("Reel","Storytelling","chat",
  "El mensaje de un cliente que resume por qué hago esto",
  "Captura emotiva y creíble del impacto real de ordenar números + visibilidad + IA.",
  "Guárdalo"),
 ("Carrusel","IA","lista",
  "5 tareas de tu negocio que la IA puede hacer esta misma semana",
  "Lista práctica y concreta por área: contenido, atención, administración, análisis.",
  "Escríbeme IA"),
 ("Historia","Autoridad","chat",
  "Así suena una recomendación que sí trae clientes",
  "Captura de un testimonio espontáneo: la prueba social específica gana a la genérica.",
  "Escríbeme AUTORIDAD"),
 ("Reel","Conversión","nota",
  "Dejé de perseguir clientes el día que entendí esto",
  "Confesión en formato nota: atraer en vez de perseguir empieza por un mensaje claro.",
  "Escríbeme SISTEMA"),
 ("Carrusel","Crecimiento","versus",
  "Empresa que depende de ti vs empresa que funciona sin ti",
  "Dos columnas: el negocio-esclavo frente al negocio-sistema. Cómo pasar de uno a otro.",
  "Guárdalo"),
 ("Post","Mentalidad","frase",
  "Crecer con calma no es ir lento. Es no romper lo que ya funciona.",
  "Reflexión sobre crecimiento sostenible frente a la prisa que quema negocios.",
  "¿Estás de acuerdo? Cuéntamelo"),
 ("Reel","Marketing","chat",
  "El primer mensaje que me escriben cuando el contenido hace su trabajo",
  "Captura de cierre de mes: el contenido bien hecho llena la agenda sin perseguir a nadie.",
  "Escríbeme ESTRATEGIA"),
]

filas = []
for i, (fmt, pilar, tipo, gancho, idea, cta) in enumerate(PLAN):
    fecha = INICIO + datetime.timedelta(days=i)
    filas.append({
        "Nº": i + 1,
        "Fecha": fecha.isoformat(),
        "Día": DIAS_ES[fecha.weekday()],
        "Formato": fmt,
        "Pilar": pilar,
        "Tipo de slide": tipo,
        "Gancho": gancho,
        "Idea central": idea,
        "CTA": cta,
        "Estado": "Pendiente",
    })

cols = ["Nº","Fecha","Día","Formato","Pilar","Tipo de slide","Gancho","Idea central","CTA","Estado"]
salida = "calendario_viral_30dias_rosa_maria.csv"
with open(salida, "w", encoding="utf-8-sig", newline="") as f:
    w = csv.DictWriter(f, fieldnames=cols)
    w.writeheader()
    w.writerows(filas)
print("OK", salida, len(filas), "días")
